  name: Lint

  on: push

  jobs:
    run-linters:
      name: Run linters
      runs-on: ubuntu-latest

      steps:
        - name: Check out Git repository
          uses: actions/checkout@v2

       # TODO: Install your linters here
       - name: Set up Python
         uses: actions/setup-python@v1
         with:
           python-version: 3.xx

       - name: Install Python dependencies
         run: pip install black flake8

        - name: Run linters
          uses: samuelmeuli/lint-action@v1
          with:
            github_token: ${{ secrets.github_token }}
           # TODO: Enable your linters here
           black: true
           flake8: true
